import { LightningElement } from 'lwc';

const STANDARD_ICONS = [
    'account','account_info','account_score','action_list_component','action_override',
    'actions_and_buttons','activation_target','activations','ad_event_action','ad_event_cause',
    'ad_event_effect','ad_event_factor','ad_event_info','ad_event_outcome','ad_event_party',
    'address','adverse_event','agent_astro','agent_home','agent_session','aggregate',
    'aggregation_policy','ai_accelerator_card','ai_slack_summary','all','announcement',
    'answer_best','answer_private','answer_public','apex','apex_plugin','app',
    'app_form_participant','app_form_product_participant','approval','apps','apps_admin',
    'article','asset_action','asset_action_source','asset_audit','asset_downtime_period',
    'asset_hierarchy','asset_object','asset_relationship','asset_state_period','asset_warranty',
    'assigned_resource','assignment','attach','attribute_based_pricing','avatar','avatar_loading',
    'bill_of_materials','billing','bot','bot_training','branch_merge','brand','budget',
    'budget_allocation','budget_category_value','budget_period','bundle_config','bundle_policy',
    'bundles_pricing','business_hours','business_unit','buyer_account','buyer_group',
    'buyer_group_qualifier','calculated_dimension','calculated_insights','calculated_measure',
    'calibration','call','call_coaching','call_history','campaign','campaign_members',
    'cancel_checkout','canvas','capacity_plan','care_request_reviewer','carousel','case',
    'case_change_status','case_comment','case_email','case_log_a_call','case_milestone',
    'case_transcript','case_wrap_up','catalog','category','change_request','changes',
    'channel_program_history','channel_program_levels','channel_program_members','channel_programs',
    'chart','checkout','choice','client','cms','coaching','code_playground','code_set',
    'code_set_bundle','collection','collection_alt','collection_variable','connect_wallet',
    'connected_apps','constant','contact','contact_list','contact_request','contract',
    'contract_line_item','contract_line_outcome','contract_line_outcome_data','contract_payment',
    'cost_model','coupon_codes','currency','currency_input','custom','custom_component_task',
    'custom_entity','custom_notification','custom_textbox','customer','customer_360',
    'customer_lifecycle_analytics','customer_portal_users','customer_workspace','customers',
    'dashboard','dashboard_component','dashboard_ea','data_cloud','data_governance','data_graph',
    'data_integration_hub','data_lake_objects','data_mapping','data_model','data_streams',
    'data_transforms','database','datadotcom','dataset','date_input','date_time','decision',
    'default','delegated_account','device','document','document_preview','document_reference',
    'drafts','dynamic_highlights_panel','dynamic_record_choice','edit_form','education',
    'einstein_replies','email','email_chatter','employee','employee_asset','employee_contact',
    'employee_job','employee_job_position','employee_organization','empty','end_call',
    'endorsement','entitlement','entitlement_policy','entitlement_process','entitlement_template',
    'entity','entity_milestone','entity_milestone_date','entity_milestone_time','environment_hub',
    'event','event_ext','events','expense','expense_report','expense_report_entry',
    'facility_bed','feed','feedback','field_sales','file','filter','flow','folder','forecasts',
    'form','formula','fulfillment_order','funding_award_adjustment','funding_requirement',
    'goals','group_loading','groups','guidance_center','hierarchy','high_velocity_sales',
    'home','household','identifier','immunization','impact_outcome','impact_strategy',
    'impact_strategy_assignment','in_app_messaging','inbox','incident','individual','insights',
    'instore_locations','investment_account','iot_context','iot_orchestrations',
    'it_service_management','kanban','key_dates','knowledge','labels','lead','lead_insights',
    'lead_list','learner_program','letterhead','life_sciences','lightning_component',
    'lightning_usage','link','linked','list_email','live_chat','live_chat_visitor','location',
    'location_permit','log_a_call','logging','loop','macros','maintenance_asset',
    'maintenance_plan','maintenance_work_rule','market','marketing_actions','mcp_server',
    'medication','medication_administration','medication_dispense','medication_ingredient',
    'medication_reconciliation','medication_statement','member_period','merge',
    'messaging_conversation','messaging_session','messaging_user','metric','metric_definition',
    'metrics','mulesoft','network_contract','news','note','number_input','omni_channel',
    'omni_supervisor','operating_hours','operation_plan','operation_plan_execution',
    'operation_plan_request','operation_plan_step','operation_plan_step_execution','opportunity',
    'opportunity_contact_role','opportunity_splits','orchestrator','order_item','orders',
    'outcome','outcome_activity','outcome_datebound','outcome_timebound','output',
    'panel_detail','partner_fund_allocation','partner_fund_claim','partner_fund_request',
    'partner_marketing_budget','partners','party_profile','password','past_chat',
    'path_experiment','payment_gateway','people','people_score','performance','person_account',
    'person_language','person_name','photo','picklist_choice','picklist_type','planogram',
    'play','policy','poll','portal','portal_roles','portal_roles_and_subordinates','post',
    'practitioner_role','prep_flow','price_adjustment_matrix','price_adjustment_schedule',
    'price_adjustment_tier','price_book_entries','price_books','price_sheet','pricebook',
    'pricing_workspace','problem','procedure','process','process_exception','product',
    'product_consumed','product_consumed_state','product_item','product_item_transaction',
    'product_quantity_rules','product_request','product_request_line_item','product_required',
    'product_service_campaign','product_service_campaign_item','product_transfer',
    'product_transfer_state','product_warranty_term','product_workspace','products',
    'program_cohort','program_cohort_member','program_detail','program_site','program_status',
    'promotion_segments','promotion_tiers','promotions','promotions_workspace','prompt',
    'prompt_builder','proposition','prospect','push','qualifications','question_best',
    'question_feed','queue','quick_text','quip','quip_sheet','quotes','recipe','record',
    'record_consent','record_create','record_delete','record_lookup','record_signature_task',
    'record_update','recycle_bin','registered_model','related_list','relationship',
    'report','report_type','reset_password','resource_absence','resource_capacity',
    'resource_preference','resource_skill','restriction_policy','return_order',
    'return_order_line_item','reward','robot','sales_cadence','sales_cadence_target',
    'sales_channel','sales_path','sales_value','salesforce_cms','schedule_objective',
    'scheduling_constraint','scheduling_policy','scheduling_workspace',
    'scheduling_workspace_territory','screen','search','segments','selling_model','send_log',
    'serialized_product','serialized_product_transaction','service_appointment',
    'service_appointment_capacity_usage','service_contract','service_crew',
    'service_crew_member','service_report','service_request','service_request_detail',
    'service_resource','service_territory','service_territory_location',
    'service_territory_member','service_territory_policy','settings','setup_modal','shift',
    'shift_pattern','shift_pattern_entry','shift_preference','shift_scheduling_operation',
    'shift_template','shift_type','shipment','similar_case','skill','skill_entity',
    'skill_requirement','slack','slack_conversations','slider','sms','snippet','snippet_alt',
    'snippets','sobject','sobject_collection','social','solution','sort','sort_policy',
    'sparkles','stage','stage_collection','steps','store','store_group','story','strategy',
    'study','sub_metric','submit_for_approval','survey','swarm_request','swarm_session',
    'system_and_global_variable','table','tableau','tabset','task','task2','tax_policy',
    'tax_rate','tax_treatment','taxonomy','team_member','template','text','text_template',
    'textarea','textbox','thanks','thanks_loading','time_period','timesheet','timesheet_entry',
    'timeslot','today','toggle','topic','topic2','tour','tour_check','trailhead','trailhead_alt',
    'transaction_usage_entitlement','travel_mode','unified_health_score','unmatched',
    'uploaded_model','user','user_role','variable','variation_attribute_setup',
    'variation_products','video','visit_templates','visits','visualforce_page','voice_call',
    'volume_discounts','walkthroughs','warranty_term','water','webcart','whatsapp',
    'work_capacity_limit','work_capacity_usage','work_contract','work_forecast','work_order',
    'work_order_item','work_plan','work_plan_rule','work_plan_template',
    'work_plan_template_entry','work_queue','work_step','work_step_template','work_summary',
    'work_type','work_type_group','workforce_engagement','workspace','your_account',
].map(name => ({ name: `standard:${name}`, label: `standard:${name}` }));

const UTILITY_ICONS = [
    'account','activity','ad_set','add','add_above','add_below','add_source','adduser',
    'adjust_value','advanced_function','advertising','agent_astro','agent_home','agent_session',
    'aggregate','aggregation_policy','ai_app','ai_search','alert','all','analytics_extended',
    'analytics_promoted','analytics_referenced','analytics_reused','anchor','angle',
    'animal_and_nature','announcement','answer','answered_twice','anywhere_alert','anywhere_chat',
    'apex','apex_alt','apex_plugin','app_web_messaging','applied_amount','approval','apps',
    'archive','array','arrow_bottom','arrow_left','arrow_right','arrow_top','arrowdown',
    'arrowup','asset_audit','asset_object','asset_repossessed','asset_warranty','assignment',
    'attach','automate','away','back','ban','billing','block_visitor','bold','bookmark',
    'bookmark_alt','bookmark_stroke','border_all','border_bottom','border_left','border_right',
    'border_top','bottom_align','bottom_group_alignment','breadcrumbs','broadcast','brush',
    'bucket','budget_category_value','budget_period','bug','builder','bundle_config',
    'bundle_policy','button_choice','buyer_group_qualifier','calculated_insights','call',
    'campaign','cancel_file_request','cancel_transfer','cant_sync','capacity_plan','capslock',
    'captions','card_details','cart','case','cases','center_align','center_align_text',
    'center_group_alignment','change_owner','change_record_type','change_request','changes',
    'chart','chat','check','checkin','checkout','chevrondown','chevronleft','chevronright',
    'chevronup','choice','circle','classic_interface','clear','clock','close','cms',
    'collapse_all','collection','collection_alt','collection_variable','color_swatch','columns',
    'comments','company','component_customization','connected_apps','constant','contact',
    'contact_request','contactless_pay','contract','contract_alt','contract_doc',
    'contract_line_outcome','contract_line_outcome_data','contract_payment','copy',
    'copy_to_clipboard','coupon_codes','crossfilter','currency','currency_input','custom_apps',
    'customer','customer_workspace','cut','dash','data_cloud','data_graph','data_lake_objects',
    'data_mapping','data_model','data_transforms','database','datadotcom','dataspace',
    'dataspaces','date_input','date_time','dayview','delete','deny_access_field',
    'deny_access_object','deny_access_row','deprecate','description','desktop',
    'desktop_and_phone','desktop_console','detach','dialing','diamond','discounts','dislike',
    'display_rich_text','display_text','dock_panel','document_preview','donut_chart','down',
    'download','drag','drag_and_drop','duration_downscale','dx_branch','dx_change_request',
    'dx_commit','dx_org_dev','dx_org_production','dx_org_scratch','dx_org_test','dx_pipeline',
    'dynamic_record_choice','edit','edit_form','edit_gpt','education','einstein','einstein_alt',
    'email','email_open','emoji','emoji_above_average','emoji_average','emoji_bad',
    'emoji_below_average','emoji_excellent','emoji_good','emoji_outstanding','emoji_very_bad',
    'emoji_very_good','emoji_worst','end_call','end_chat','end_messaging_session','engage',
    'enter','entitlement','environment_hub','erect_window','error','event','event_ext',
    'events','expand','expand_all','expand_alt','expense','expense_report','expired',
    'fallback','favorite','favorite_alt','feed','file','filter','filter_criteria',
    'filter_criteria_rule','flow','flow_alt','food_and_drink','form','format','formula',
    'forward','forward_up','freeze_column','frozen','fulfillment_order','full_width_view',
    'fully_synced','funding_award_adjustment','funding_requirement','global_constant','graph',
    'groups','guidance','heart','height','help','help_center','help_doc_ext','hide',
    'hide_mobile','hierarchy','high_velocity_sales','highlight','holiday_operating_hours',
    'home','hourglass','http','identified_guest','identity','image','in_app_assistant',
    'inbox','incident','incoming_call','indicator_performance_period','info','info_alt',
    'inner_join','insert_tag_field','insert_template','inspector_panel','integration',
    'internal_share','it_service_management','italic','join','jump_to_bottom','jump_to_left',
    'jump_to_right','jump_to_top','justify_text','kanban','key','key_dates','keyboard_dismiss',
    'keypad','knowledge_base','knowledge_smart_link','label','labels','language_settings',
    'layers','layout','layout_banner','layout_card','layout_overlap','layout_tile','lead',
    'leave_conference','left','left_align','left_align_text','left_join','level_down',
    'level_up','light_bulb','lightning_extension','lightning_inspector','like','line_chart',
    'link','linked','list','list_email','listen','live_message','location','location_permit',
    'lock','locked_with_additions','log_a_call','logout','loop','macros','magicwand',
    'maintenance_plan','mark_all_as_read','market','mask_field','matrix','merge',
    'merge_field','messaging_conversation','metrics','minimize_window','missed_call',
    'mixed_sources_mapping','money','moneybag','monthlyview','more','move','mulesoft',
    'multi_picklist','multi_select_checkbox','muted','new','new_direct_message','new_window',
    'news','no_return','not_in_sync','not_saved','note','notebook','notification',
    'notification_off','notification_snoozed','number_input','office365','offline',
    'offline_briefcase','offline_cached','omni_channel','omni_supervisor','open','open_folder',
    'opened_folder','opportunity','orchestrator','orders','org_chart','outbound_call','outcome',
    'outer_join','output','overflow','package_org','package_org_beta','page','page_structure',
    'palette','partner_fund_request','password','paste','path_experiment','pause','pause_alt',
    'paused_call','payment_gateway','people','people_score','percent','phone_landscape',
    'phone_portrait','photo','picklist','picklist_choice','picklist_type','pin','pinned',
    'plane','planning_poker','play','podcast_webinar','policy','pop_in','power','preview',
    'price_book_entries','price_books','price_sheet','pricing_workspace','print','priority',
    'privately_shared','pro_network','problem','process','product','product_consumed_state',
    'product_quantity_rules','product_service_campaign','product_service_campaign_item',
    'product_transfer','product_transfer_state','product_warranty_term','product_workspace',
    'products','profile','profile_alt','program_cohort','program_cohort_member',
    'promotion_segments','promotion_tiers','promotions','promotions_workspace','prompt',
    'prompt_builder','prompt_edit','propagation_policy','proposition','push','puzzle',
    'qualifications','question','question_mark','questions_and_answers','queue','quick_text',
    'quip','quotation_marks','quote','radio_button','rating','real_time','reassign','recipe',
    'record','record_alt','record_collection','record_consent','record_create','record_delete',
    'record_lookup','record_update','recurring_exception','recycle_bin_empty','recycle_bin_full',
    'redo','refresh','regenerate','relate','reminder','remove_formatting','remove_link',
    'replace','replay','reply','reply_all','report_issue','reset_password','resource_absence',
    'resource_capacity','resource_territory','restriction_policy','retail_execution','retweet',
    'ribbon','richtextbulletedlist','richtextindent','richtextnumberedlist','richtextoutdent',
    'right','right_align','right_align_text','right_join','robot','rotate','routing_offline',
    'rows','rules','sales_channel','salesforce_page','salesforce1','save','scan','screen',
    'search','section','segments','send','send_log','sender_email','sentiment_negative',
    'sentiment_neutral','serialized_product','serialized_product_transaction',
    'service_appointment','service_contract','service_report','service_territory_policy',
    'settings','setup','setup_assistant_guide','setup_modal','share','share_file',
    'share_mobile','share_post','shield','shift_pattern','shift_pattern_entry',
    'shift_scheduling_operation','shift_ui','shopping_bag','shortcuts','side_list','signature',
    'signpost','similar_case','skill','skip','skip_back','skip_forward','slack',
    'slack_add_reaction','slack_ai_summary','slack_channel','slack_conversations',
    'slack_formatting','slack_huddles','slack_lock','slack_lock_filled','slack_mentions',
    'slack_notifications_off','slack_notifications_on','slack_thread','slack_thumbs_down',
    'slack_thumbs_up','slack_trash','slack_user','slack_user_add','slack_user_group','slider',
    'smiley_and_people','sms','snippet','sobject','sobject_collection','socialshare','sort',
    'sort_ascending','sort_policy','spacer','sparkle','sparkles','spinner','stage',
    'stage_collection','standard_objects','status_code','steps','stop','store','strategy',
    'strikethrough','submit_for_approval','success','suggested_for_you','summary',
    'summarydetail','survey','swarm_request','swarm_session','switch','symbols','sync',
    'sync_in_progress','system_and_global_variable','table','table_settings','tableau',
    'tablet_landscape','tablet_portrait','tabset','talent_development','target','target_mode',
    'task','tax_policy','tax_rate','tax_treatment','text','text_background_color','text_color',
    'text_template','textarea','textbox','threedots','threedots_vertical','thunder',
    'tile_card_list','toggle','toggle_off','toggle_on','toggle_panel_bottom','toggle_panel_left',
    'toggle_panel_right','toggle_panel_top','tollways','top_align','top_group_alignment',
    'topic','topic2','touch_action','tour','tour_check','tracker','trail','trailblazer_ext',
    'trailhead','trailhead_alt','trailhead_ext','translate','transparent','travel_and_places',
    'trending','truck','turn_off_notifications','type','type_tool','undelete','undeprecate',
    'underline','undo','unlinked','unlock','unmuted','up','upload','user','user_role',
    'variable','variation_attribute_setup','variation_products','video','video_off',
    'visibility_rule_assigned','voicemail_drop','voicemail_drop_alt','volume_high','volume_low',
    'volume_off','waits','walkthroughs','warning','warranty_term','watchlist','water',
    'weeklyview','wellness','width','wifi','work_forecast','work_order_type','work_queue',
    'workforce_engagement','world','your_account','yubi_key','zoomin','zoomout',
].map(name => ({ name: `utility:${name}`, label: `utility:${name}` }));

const ACTION_ICONS = [
    'add_contact','add_file','add_photo_video','add_relationship','adjust_value',
    'announcement','apex','approval','back','bug','call','canvas','change_owner',
    'change_record_type','check','clone','close','defer','delete','description','dial_in',
    'download','edit','edit_groups','edit_relationship','email','fallback','filter','flow',
    'follow','following','freeze_user','goal','info','join_group','lead_convert','leave_group',
    'log_a_call','log_event','manage_perm_sets','map','more','new','new_account','new_campaign',
    'new_case','new_child_case','new_contact','new_event','new_group','new_lead','new_note',
    'new_notebook','new_opportunity','new_person_account','new_task','password_unlock',
    'preview','priority','question_post_action','quote','recall','record','refresh','reject',
    'remove','remove_relationship','reset_password','script','share','share_file','share_link',
    'share_poll','share_post','share_thanks','sort','submit_for_approval','update',
    'update_status','upload','user','user_activation','view_relationship','web_link',
].map(name => ({ name: `action:${name}`, label: `action:${name}` }));

const DOCTYPE_ICONS = [
    'ai','attachment','audio','box_notes','css','csv','eps','excel','exe','flash','folder',
    'gdoc','gdocs','gform','gpres','gsheet','html','image','keynote','library_folder','link',
    'mp4','overlay','pack','pages','pdf','ppt','psd','quip_doc','quip_sheet','quip_slide',
    'rtf','shared_folder','slack_canvas','slack_list_item','slack_lists','slide','stypi',
    'txt','unknown','video','visio','webex','word','xml','zip',
].map(name => ({ name: `doctype:${name}`, label: `doctype:${name}` }));

export default class IconTest extends LightningElement {
    renderTime = null;
    _renderStart = null;

    connectedCallback() {
        this._renderStart = performance.now();
    }

    renderedCallback() {
        if (this.renderTime === null) {
            this.renderTime = (performance.now() - this._renderStart).toFixed(1);
        }
    }

    get standardIcons() { return STANDARD_ICONS; }
    get utilityIcons()  { return UTILITY_ICONS; }
    get actionIcons()   { return ACTION_ICONS; }
    get doctypeIcons()  { return DOCTYPE_ICONS; }

    get standardCount() { return STANDARD_ICONS.length; }
    get utilityCount()  { return UTILITY_ICONS.length; }
    get actionCount()   { return ACTION_ICONS.length; }
    get doctypeCount()  { return DOCTYPE_ICONS.length; }
    get totalCount()    { return STANDARD_ICONS.length + UTILITY_ICONS.length + ACTION_ICONS.length + DOCTYPE_ICONS.length; }

    get renderTimeLabel() {
        return this.renderTime !== null ? `${this.renderTime} ms` : '—';
    }
}
